### ISSUE TITLE
Updating Payment Info 500 Error

### ISSUE THREAD

**Issue by jonnykry** [jonnykry/expresso#95]
# Issue

I tried updating my payment info for my acct (jonnykry93@gmail.com) and got a 500 error.  Not sure what the error is without looking into logs.  Some "Unable to Parse Token" thing.

**Comment by ghmeier** [comment]
This is intentional. We have stripe set to test mode so it will only accept test credentials https://stripe.com/docs/testing and we're just using the test keys. 

My thought is that we should just keep it that way throughout and we can tell people who we demo one of the fake credentials to use.

edit: but we also need to set the key. thought i fixed that but woops.
